version: 2.0
jobs:
    build:
        working_directory: ~/circleci_temp/react-redux-starter-kit
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - restore_cache:
                key: -v.x-{{ checksum "requirements/dev.txt" }}
            - run: npm install
            - run: npm test
            - save_cache:
                key: -v.x-{{ checksum "requirements/dev.txt" }}
                paths:
                    - "."
